In [144]:
import pandas as pd
from pandas import DataFrame
import pyarrow as pa
import pyarrow.parquet as pq
from datetime import datetime
import sys
import csv
csv.field_size_limit(sys.maxsize)

9223372036854775807

In [145]:
chainfile = open('/Users/raju.pillai/gitrepo/python/data/DataAcquisition/source/dimensions/chain.txt','r')
brandfile = open('/Users/raju.pillai/gitrepo/python/data/DataAcquisition/source/dimensions/brand.txt','r')
propertyfile = open('/Users/raju.pillai/gitrepo/python/data/DataAcquisition/source/dimensions/property.txt','r')

In [146]:
chaindata = DataFrame(pd.read_csv(chainfile, sep='|', engine='python'))
branddata = DataFrame(pd.read_csv(brandfile, sep='|', engine='python'))
propertydata = DataFrame(pd.read_csv(propertyfile, sep='|', engine='python'))

In [147]:
#print (list(propertydata.columns))

In [148]:
chain_brand_combined_df = pd.merge(chaindata, branddata, left_on='chain_code', right_on='chain_code', how='inner')

In [149]:
property_chain_brand_combined_df = pd.merge(chain_brand_combined_df, propertydata, left_on='brand', right_on='property_brand', how='inner' )

In [151]:
#for col in property_chain_brand_combined_df.columns: 
#   print(col)

In [152]:
dimension_data = (property_chain_brand_combined_df[[
     'chain_code'
    ,'chain_name'
    ,'brand'
    ,'brand_name'
    ,'pid'
    ,'property_name'
    ,'property_city'
    ,'property_state'
    ,'hcc_trans_fee'
    ,'nonhcc_transfee'
    ,'nonhcc_chkfee_dom'
    ,'hcc_chkfee_dom'
]]).astype(str)

In [153]:
#dimension_data.columns

In [155]:
dataset95 = DataFrame(pd.read_parquet('/Users/raju.pillai/gitrepo/python/data/DataAcquisition/output/pqt/osfdata_part_parquet95'))
#dataset95 = DataFrame(pd.read_parquet('/Users/raju.pillai/gitrepo/python/data/DataAcquisition/output/stay/osfdata_part_parquet'))

In [156]:
#dataset95.columns

In [157]:
longdataset95 = pd.merge(dataset95, dimension_data, left_on=['Chain_Property_ID'], right_on=['pid'] ,how='left').reset_index()

In [158]:
longdataset95.to_parquet(fname = '/Users/raju.pillai/gitrepo/python/data/DataAcquisition/output/pqt/osfdata_cash_part_long_parquet',partition_cols=['Brand_Code'], compression='none')

In [129]:
#table = pa.Table.from_pandas(longdataset95)

In [48]:
#table

In [130]:
#table.to_pandas()

,index,File_Source,File_Timestamp,Record_Type,Payment_Record_Type,Action_Code,Payment_Record_Number,Chain_Property_ID,Booking_Source,Chain_Confirmation_Number,...,brand,brand_name,pid,property_name,property_city,property_state,hcc_trans_fee,nonhcc_transfee,nonhcc_chkfee_dom,hcc_chkfee_dom
0,0,Cash-95,2019-10-22 15:10:35,,CD2,HCC,PR1807251056,1056,9.5,None,...,HW,HOTEL WORLD,1056,HOBERGER LANDHAUS,BIELEFELD,nan,55.0,110.0,0.0,0.0
1,1,Cash-95,2019-10-22 15:10:35,,CD2,HCC,PR1807251056,1056,9.5,None,...,XM,MERCURE,1056,MERCURE RENNES CENTRE PARLEMEN,RENNES,,74.0,0.0,0.0,0.0
2,2,Cash-95,2019-10-22 15:10:35,,CD2,HCC,PR1807251056,1056,9.5,None,...,6N,SUPRANATIONAL-P,1056,GRAND HOTEL,COPENHAGEN,nan,0.0,0.0,0.0,0.0
3,3,Cash-95,2019-10-22 15:10:35,,01,A,249847689,46504,HRS,49295436,...,HW,HOTEL WORLD,46504,BEAUCLIFFE HOTEL,BLACKPOOL,nan,55.0,110.0,0.0,0.0
4,4,Cash-95,2019-10-22 15:10:35,,01,A,249847689,46504,HRS,49295436,...,UI,PEGASUS CONNECT UI,46504,BUENA PARK HOTEL AND CONV CENT,BUENA PARK,CA,75.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1799977,1799977,Cash-95,2019-10-22 15:10:35,,nan,nan,nan,nan,nan,nan,...,None,None,None,None,None,None,None,None,None,None
1799978,1799978,Cash-95,2019-10-22 15:10:35,,nan,nan,nan,nan,nan,nan,...,None,None,None,None,None,None,None,None,None,None
1799979,1799979,Cash-95,2019-10-22 15:10:35,,nan,nan,nan,nan,nan,nan,...,None,None,None,None,None,None,None,None,None,None
1799980,1799980,Cash-95,2019-10-22 15:10:35,,nan,nan,nan,nan,nan,nan,...,None,None,None,None,None,None,None,None,None,None
1799981,1799981,Cash-95,2019-10-22 15:10:35,,nan,nan,nan,nan,nan,nan,...,None,None,None,None,None,None,None,None,None,None

In [50]:
# pq.write_table(table, '/Users/raju.pillai/gitrepo/python/data/DataAcquisition/output/pqt/osfdata.parquet',compression='none')

In [53]:
# pq.write_to_dataset(table, root_path = '/Users/raju.pillai/gitrepo/python/data/DataAcquisition/output/pqt/osfdata_part_parquet95',partition_cols=['Brand_Code'], compression='none', use_dictionary=False)